name: Test - Proto Gen

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bufbuild/buf-action@v1
    - name: Build Tool
      run: |
        docker -v
        make proto-gen
        
